### ISSUE TITLE
Generatie van Style Sheet lijkt iets te missen

### ISSUE THREAD

**Issue by Colin-TUE** [Brutusn/ScoutingVeghel#73]
Het ljk erop dat de sectie voor de ouders in mobile view (basis setup) de beige achterground rkijgen, maar in de desktop view krijgt het de bruine achtergrond.

Kan dit zien in de `style.min.css`:
```css
.ouders {
  background-color: #dddac4;
}
``` 
maar moet 
```css
.ouders {
  background-color: #2E2F2A;
}
```
zijn.

De tekst lijkt wel goed te gaan.
